window.appData = {
  avatar: [
    {
      id: 1,
      src: "./assets/img/fenek.jpg",
      alt: "Fenek",
      health: 150,
      wins: 0,
      loses: 0,
    },
    {
      id: 2,
      src: "./assets/img/berkut.jpg",
      alt: "Berkut",
      health: 200,
      wins: 0,
      loses: 0,
    },
    {
      id: 3,
      src: "./assets/img/cat.jpg",
      alt: "Cat",
      health: 150,
      wins: 0,
      loses: 0,
    },
    {
      id: 4,
      src: "./assets/img/varan.jpg",
      alt: "Varan",
      health: 100,
      wins: 0,
      loses: 0,
    },
    {
      id: 5,
      src: "./assets/img/peregusna.jpg",
      alt: "Peregusna",
      health: 150,
      wins: 0,
      loses: 0,
    },
  ],
  enemy_avatar: [
    {
      id: 1,
      src: "./assets/img/cobra.jpg",
      alt: "Cobra",
      health: 100,
      count_attack: 1,
      count_block: 2,
      wins: 0,
      loses: 0,
    },
    {
      id: 2,
      src: "./assets/img/viper.jpg",
      alt: "Viper",
      health: 150,
      count_attack: 2,
      count_block: 1,
      wins: 0,
      loses: 0,
    },
    {
      id: 3,
      src: "./assets/img/scorpion.jpg",
      alt: "Scorpion",
      health: 200,
      count_attack: 2,
      count_block: 3,
      wins: 0,
      loses: 0,
    },
  ],
  attack: [
    { id: 1, label: "Тыдыщ!", points: 20 },
    { id: 2, label: "Кусь", points: 15 },
    { id: 3, label: "Хрясь", points: 15 },
    { id: 4, label: "Тьфу", points: 10 },
    { id: 5, label: "Два Куся", points: 30 },
  ],
};

// const avatar = [
//   { id: 1, src: "./assets/img/fenek.jpg", alt: "Fenek", health: 150 },
//   { id: 2, src: "./assets/img/berkut.jpg", alt: "Berkut", health: 200 },
//   { id: 3, src: "./assets/img/cat.jpg", alt: "Cat", health: 150 },
//   { id: 4, src: "./assets/img/varan.jpg", alt: "Varan", health: 100 },
//   {
//     id: 5,
//     src: "./assets/img/peregusna.jpg",
//     alt: "Peregusna",
//     health: 150,
//   },
// ];
// const enemy_avatar = [
//   {
//     id: 1,
//     src: "./assets/img/cobra.jpg",
//     alt: "Cobra",
//     health: 100,
//     count_attack: 1,
//     count_block: 2,
//   },
//   {
//     id: 2,
//     src: "./assets/img/viper.jpg",
//     alt: "Viper",
//     health: 150,
//     count_attack: 2,
//     count_block: 1,
//   },
//   {
//     id: 3,
//     src: "./assets/img/scorpion.jpg",
//     alt: "Scorpion",
//     health: 200,
//     count_attack: 2,
//     count_block: 3,
//   },
// ];
